# Generated by Django 2.2.7 on 2020-01-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='scores',
            field=models.FloatField(default=0),
        ),
    ]
